# Predict

1. Используемый датасет: GTZAN dataset.  
http://marsyasweb.appspot.com/download/data_sets/
2. Используемый алгоритм для экстракции фич: mfcc - более подробно в комментариях  
Библиотека: python_speech_features 

---

3. Что еще нужно?  
  - Бороться с переобучением

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from copy import copy

import python_speech_features as psf
import sunau
import librosa as lb

from sklearn.preprocessing import LabelEncoder

In [6]:
#Проверим загружаемость
audio_files_load = pd.read_csv('dataset.csv',index_col=0, sep=",", dtype=object)
audio_files_load

genre       file_name samplerate duration  \
0    blues  blues.00000.au      22050       30   
1    blues  blues.00001.au      22050       30   
2    blues  blues.00002.au      22050       30   
3    blues  blues.00003.au      22050       30   
4    blues  blues.00004.au      22050       30   
5    blues  blues.00005.au      22050       30   
6    blues  blues.00006.au      22050       30   
7    blues  blues.00007.au      22050       30   
8    blues  blues.00008.au      22050       30   
9    blues  blues.00009.au      22050       30   
10   blues  blues.00010.au      22050       30   
11   blues  blues.00011.au      22050       30   
12   blues  blues.00012.au      22050       30   
13   blues  blues.00013.au      22050       30   
14   blues  blues.00014.au      22050       30   
15   blues  blues.00015.au      22050       30   
16   blues  blues.00016.au      22050       30   
17   blues  blues.00017.au      22050       30   
18   blues  blues.00018.au      22050       30   
19   blues  blues.00019.au      22050       30   
20   blues  blues.00020.au      22050       30   
21   blues  blues.00021.au      22050       30   
22   blues  blues.00022.au      22050       30   
23   blues  blues.00023.au      22050       30   
24   blues  blues.00024.au      22050       30   
25   blues  blues.00025.au      22050       30   
26   blues  blues.00026.au      22050       30   
27   blues  blues.00027.au      22050       30   
28   blues  blues.00028.au      22050       30   
29   blues  blues.00029.au      22050       30   
..     ...             ...        ...      ...   
970   rock   rock.00070.au      22050       30   
971   rock   rock.00071.au      22050       30   
972   rock   rock.00072.au      22050       30   
973   rock   rock.00073.au      22050       30   
974   rock   rock.00074.au      22050       30   
975   rock   rock.00075.au      22050       30   
976   rock   rock.00076.au      22050       30   
977   rock   rock.00077.au      22050       30   
978   rock   rock.00078.au      22050       30   
979   rock   rock.00079.au      22050       30   
980   rock   rock.00080.au      22050       30   
981   rock   rock.00081.au      22050       30   
982   rock   rock.00082.au      22050       30   
983   rock   rock.00083.au      22050       30   
984   rock   rock.00084.au      22050       30   
985   rock   rock.00085.au      22050       30   
986   rock   rock.00086.au      22050       30   
987   rock   rock.00087.au      22050       30   
988   rock   rock.00088.au      22050       30   
989   rock   rock.00089.au      22050       30   
990   rock   rock.00090.au      22050       30   
991   rock   rock.00091.au      22050       30   
992   rock   rock.00092.au      22050       30   
993   rock   rock.00093.au      22050       30   
994   rock   rock.00094.au      22050       30   
995   rock   rock.00095.au      22050       30   
996   rock   rock.00096.au      22050       30   
997   rock   rock.00097.au      22050       30   
998   rock   rock.00098.au      22050       30   
999   rock   rock.00099.au      22050       30   

                                                  mean  \
0    [ -1.50538264  -1.66745918 -15.21220703   4.23...   
1    [ -3.27341626e+00   8.52053789e-01  -2.8907873...   
2    [ -9.43213843e-01   3.49022076e+00  -1.8450147...   
3    [ -3.39170231   9.25209884  -4.38120259   4.95...   
4    [ -1.96142936   0.93701381 -23.26517463  -1.32...   
5    [ -2.13538871e+00   2.49841696e+00  -1.5173896...   
6    [ -2.11225679e+00   1.16528963e+01  -2.3602408...   
7    [ -2.247435     7.78380454 -17.76835974  10.48...   
8    [ -1.55594314  -1.90990755 -11.38929456   8.59...   
9    [ -3.07371572e+00  -3.31702137e-01  -1.2556826...   
10   [ -2.16265072e+00   9.68014302e+00  -1.9329345...   
11   [ -5.00000705   5.09507121  -4.98582962  12.98...   
12   [ -2.44952959e+00   5.33121476e+00  -1.6649586...   
13   [ -3.00262460e+00   2.44281473e+00  -4.0852536...   
14   [ -4.66073991   3.7070764   -

In [9]:
audio_files_load.iloc[0, 4]

'[ -1.50538264  -1.66745918 -15.21220703   4.23198313  -9.58464693\n   2.58241955 -18.42872884   6.35673123 -14.76404361   7.11813274\n  -7.61231446   7.73238963  -4.81976457   3.36533101  -5.88293318\n  -1.61010153  -2.58018652   0.83373388  -2.6204491    1.02039765\n  -1.43262021  -0.11374151  -0.09444546  -0.09804753   0.28404624\n  -0.70090855]'

In [16]:
# Процессинг датасета
def StringToList(string):
    string = string.replace("\n", "")
    string = string[1:-1] # Убираем квадратные скобки

    result = list()
    for s in string.split(" "):
        if s == "":
            continue
        else:
            result.append(float(s))

    return result

In [18]:
audio_files_load.iloc[:, 4:10] = audio_files_load.iloc[:, 4:10].applymap(StringToList)

In [74]:
def prepare_data(data):
    X = data.iloc[:,[4,5,6,7]].values
    y = data.iloc[:,0]
    
    res = list()
    for x in X:
        res_prep = list()
        for element in x:
            res_prep += element
        res.append(res_prep)
    X = np.array(res, dtype=np.float32)
    
    le = LabelEncoder()
    le.fit(y)
    y = le.transform(y)
    return X, y

In [87]:
X, y = prepare_data(audio_files_load)

np.random.seed(222)
random_idx = range(X.shape[0])
np.random.shuffle(random_idx)
X = X[random_idx]
y = y[random_idx]
print y

[9 3 4 6 8 7 5 1 6 1 1 6 9 5 7 0 4 0 7 1 3 4 1 3 7 7 1 8 4 4 8 5 5 6 9 6 9
 0 5 2 4 8 9 1 3 0 1 4 2 2 5 3 7 6 0 2 8 5 5 1 5 0 0 3 5 3 9 1 3 4 0 8 3 9
 8 5 2 7 9 4 9 6 3 2 0 9 2 9 5 2 6 7 0 4 2 8 4 6 7 2 6 3 9 8 6 4 3 8 6 3 8
 2 4 8 9 2 4 7 7 2 1 0 3 2 4 3 7 8 9 6 8 9 0 8 1 4 7 2 8 0 2 0 0 9 8 3 9 1
 9 3 2 1 5 1 6 0 8 2 5 3 6 0 1 2 2 4 6 1 4 1 6 7 8 0 2 9 4 2 0 3 7 3 1 1 8
 6 6 7 8 4 4 6 9 1 2 1 8 9 4 3 7 8 7 6 9 9 9 3 4 9 6 1 2 8 8 3 3 9 6 0 5 2
 3 2 4 2 5 7 5 0 7 9 8 1 0 9 0 6 6 9 0 2 0 4 2 8 8 5 7 9 4 0 9 4 9 8 7 0 5
 9 2 0 7 2 7 9 7 6 6 8 8 9 7 1 7 8 0 5 2 6 6 7 0 0 9 4 3 3 7 8 8 6 5 6 2 1
 5 5 1 0 3 5 6 7 9 7 1 0 8 2 9 6 4 6 1 6 4 5 3 1 2 2 7 5 9 3 3 0 6 1 8 8 4
 9 5 1 8 6 5 5 0 6 3 5 2 0 8 3 3 6 4 3 9 1 1 4 9 6 9 4 8 3 9 0 9 4 9 9 1 4
 3 7 1 4 0 2 8 3 7 6 0 3 1 1 0 5 5 3 0 7 7 7 8 6 7 9 2 9 8 8 1 6 9 1 1 8 3
 6 3 4 8 9 0 3 5 9 2 4 8 0 5 1 2 6 2 6 6 4 8 9 7 8 7 2 5 2 1 0 3 2 5 2 2 9
 3 7 1 7 8 6 1 5 7 2 5 3 2 7 9 4 0 7 3 1 7 9 5 8 2 2 8 3 4 4 2 6 9 6 8 2 4
 2 9 8 2 7 6 9 9 7 1 5 4 

** SVM **

In [118]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.grid_search import GridSearchCV
from sklearn.model_selection import cross_val_score

In [119]:
def select_model(x, y):
    best_accuracy = 0
    best_model = None
    
    model = SVC()
    param_grid = [{'C':[1, 10, 100],
                  'kernel':['linear']},
                  {'C':[1, 10, 100],
                  'kernel':['poly'],
                  'degree':[2,3]},
                  {'C':[1, 10, 100],
                  'kernel':['rbf'],
                  'degree':[2,3],
                  'gamma':['auto']}]

    grid = GridSearchCV(estimator=model, param_grid=param_grid, scoring='accuracy', cv=10, verbose=0)
    grid.fit(x,y)
    
    #print cross_val_score(model, x, y, scoring='accuracy')
    #accuracy = np.mean(cross_val_score(model, x, y, scoring='accuracy'))

    best_model = grid.best_estimator_
    best_accuracy = grid.best_score_
    
    best_model.fit(x, y)
    print "Best model %s, with accuracy %f" % (best_model, best_accuracy)
    return best_model, grid

In [120]:
model, grid = select_model(X, y)

Best model SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=2, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False), with accuracy 0.675000


In [121]:
grid.grid_scores_

[mean: 0.65700, std: 0.02759, params: {'kernel': 'linear', 'C': 1},
 mean: 0.65700, std: 0.02759, params: {'kernel': 'linear', 'C': 10},
 mean: 0.65700, std: 0.02759, params: {'kernel': 'linear', 'C': 100},
 mean: 0.67500, std: 0.04319, params: {'kernel': 'poly', 'C': 1, 'degree': 2},
 mean: 0.67300, std: 0.04051, params: {'kernel': 'poly', 'C': 1, 'degree': 3},
 mean: 0.67500, std: 0.04319, params: {'kernel': 'poly', 'C': 10, 'degree': 2},
 mean: 0.67300, std: 0.04051, params: {'kernel': 'poly', 'C': 10, 'degree': 3},
 mean: 0.67500, std: 0.04319, params: {'kernel': 'poly', 'C': 100, 'degree': 2},
 mean: 0.67300, std: 0.04051, params: {'kernel': 'poly', 'C': 100, 'degree': 3},
 mean: 0.19700, std: 0.02452, params: {'kernel': 'rbf', 'C': 1, 'gamma': 'auto', 'degree': 2},
 mean: 0.19700, std: 0.02452, params: {'kernel': 'rbf', 'C': 1, 'gamma': 'auto', 'degree': 3},
 mean: 0.20400, std: 0.02835, params: {'kernel': 'rbf', 'C': 10, 'gamma': 'auto', 'degree': 2},
 mean: 0.20400, std: 0.0283

In [122]:
y_hat = model.predict(X)
print sum(y_hat-y != 0) #Переобучился!

1


In [123]:
test_model = SVC(kernel='rbf', C=1, gamma='auto', degree=2)
test_model.fit(X, y)
y_hat_test = model.predict(X)
print sum(y_hat_test-y != 0)

1


In [124]:
X_train = np.delete(X, [0,100,200,300,400,500,600,700,800,900], 0)
X_test = [X[i] for i in [0,100,200,300,400,500,600,700,800,900]]
X_test = np.array(X_test)

In [125]:
y_train = np.delete(y, [0,100,200,300,400,500,600,700,800,900])
y_test = [y[i] for i in [0,100,200,300,400,500,600,700,800,900]]
y_test = np.array(y_test)

In [131]:
model.fit(X_train, y_train)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=2, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [132]:
y_hat_test = model.predict(X_test)

In [133]:
print y_hat_test
print y_test

[3 0 7 3 1 7 0 9 9 9]
[9 6 7 3 1 7 2 7 2 0]


In [134]:
accuracy_score(y_test, y_hat_test)

0.40000000000000002

In [139]:
cross_val_score(model, X, y, cv=10) #Подобранные параметры

array([ 0.58,  0.65,  0.72,  0.65,  0.68,  0.68,  0.69,  0.66,  0.69,  0.75])

In [140]:
cross_val_score(test_model, X, y, cv=10) #"Чистый" SVM, без подбора параметров

array([ 0.2 ,  0.15,  0.23,  0.16,  0.19,  0.22,  0.22,  0.2 ,  0.21,  0.19])

In [130]:
X_train.shape

(990L, 104L)